// SPDX-License-Identifier: AGPL-3.0-only
//
// Codegen + nvcc-discovery helpers for build.rs. Included via
// `#[path = "build_codegen.rs"] mod build_codegen;` so types from build.rs
// (`Target`) are reachable via `super::`.

use std::env;
use std::path::PathBuf;

use super::{SamplingCat, Target};

/// Generate the target_ptx.rs source with per-target kernel constants and
/// lookup functions.
///
/// `output_is_text` controls whether emitted constants are textual PTX
/// (`&'static str` via `include_str!`) or binary metallib/HSACO/SPIR-V
/// (`&'static [u8]` via `include_bytes!`). The two cases also pick
/// different output filenames (`.ptx` vs whatever `output_ext` says) and
/// different generated-API names (`ptx_modules` vs `metallib_modules`).
pub(super) fn generate_target_ptx_rs(
    targets: &[Target],
    all_modules: &[Vec<(String, String)>],
    output_ext: &str,
    output_is_text: bool,
) -> String {
    let mut g = String::new();
    g.push_str("// Auto-generated by build.rs — do not edit.\n");
    g.push_str("// KernelTarget and TargetPtxSet are imported by the parent lib.rs.\n\n");

    // Naming scheme switches between text PTX and binary metallib/etc:
    //   text   → `pub const FOO_PTX: &str = include_str!(...)`,
    //            `pub fn ptx_modules() -> Vec<(&str, &str)>`
    //   binary → `pub const FOO_METALLIB: &[u8] = include_bytes!(...)`,
    //            `pub fn metallib_modules() -> Vec<(&str, &[u8])>`
    // `const_ty` drops the `'static` (consts default to `'static` —
    // clippy::redundant_static_lifetimes); `modules_ty` keeps it (no
    // elision possible for function return signature).
    let (const_suffix, const_ty, include_macro, fn_root, modules_ty) = if output_is_text {
        (
            "PTX",
            "&str",
            "include_str!",
            "ptx_modules",
            "Vec<(&'static str, &'static str)>",
        )
    } else {
        (
            "METALLIB",
            "&[u8]",
            "include_bytes!",
            "metallib_modules",
            "Vec<(&'static str, &'static [u8])>",
        )
    };

    let single_target = targets.len() == 1;

    for (idx, (target, modules)) in targets.iter().zip(all_modules.iter()).enumerate() {
        let prefix = if single_target {
            String::new()
        } else {
            format!("T{idx}_")
        };

        // Kernel-blob constants
        for (stem, module_name) in modules {
            let const_name = format!("{}{}_{}", prefix, module_name.to_uppercase(), const_suffix);
            g.push_str(&format!(
                "pub const {const_name}: {const_ty} = \
                 {include_macro}(concat!(env!(\"ATLAS_PTX_DIR\"), \"/t{idx}__{stem}.{output_ext}\"));\n"
            ));
        }
        g.push('\n');

        // Per-target lookup function
        let fn_name = if single_target {
            fn_root.to_string()
        } else {
            format!("{fn_root}_t{idx}")
        };
        g.push_str(&format!(
            "/// Kernel modules for target: ({}, {}, {}).\n",
            target.hw, target.model, target.quant
        ));
        g.push_str(&format!(
            "pub fn {fn_name}() -> {modules_ty} {{\n    vec![\n"
        ));
        for (_, module_name) in modules {
            let const_name = format!("{}{}_{}", prefix, module_name.to_uppercase(), const_suffix);
            g.push_str(&format!("        (\"{module_name}\", {const_name}),\n"));
        }
        g.push_str("    ]\n}\n\n");
    }

    // For metal targets, emit empty stubs of the cuda-side API so the
    // existing surface (`ptx_modules`, `all_ptx_sets`) still type-checks.
    // Real Metal consumers read from `metallib_modules()` (above).
    if !output_is_text {
        g.push_str(
            "/// Empty PTX stub — this build targets a non-CUDA backend.\n\
             /// Use `metallib_modules()` (or the equivalent backend API).\n\
             pub fn ptx_modules() -> Vec<(&'static str, &'static str)> { Vec::new() }\n\
             \n\
             /// Empty PTX-set stub for non-CUDA targets.\n\
             pub fn all_ptx_sets() -> Vec<TargetPtxSet> { Vec::new() }\n\n",
        );
        return g;
    }

    // For multi-target builds, add backward-compat ptx_modules() alias
    if !single_target {
        g.push_str(
            "/// PTX modules for the default (first) target.\n\
             ///\n\
             /// Backward-compatible alias. Prefer `all_ptx_sets()` for multi-target builds.\n\
             pub fn ptx_modules() -> Vec<(&'static str, &'static str)> {\n\
             \x20   ptx_modules_t0()\n\
             }\n\n",
        );
    }

    // all_ptx_sets() function — always generated for cuda targets
    g.push_str(
        "/// All compiled kernel targets and their PTX module sets.\n\
         pub fn all_ptx_sets() -> Vec<TargetPtxSet> {\n\
         \x20   vec![\n",
    );
    for (idx, target) in targets.iter().enumerate() {
        // Strip trailing 'f' from arch for KernelTarget (sm_121f → sm_121)
        let arch_clean = target.arch.trim_end_matches('f');
        let fn_name = if single_target {
            "ptx_modules".to_string()
        } else {
            format!("ptx_modules_t{idx}")
        };
        let fmt_cat = |c: &SamplingCat| -> String {
            format!(
                "SamplingCategory {{ temperature: {:.2}, top_p: {:.2}, top_k: {}, presence_penalty: {:.2}, frequency_penalty: {:.2}, repetition_penalty: {:.2}, dry_multiplier: {:.2}, dry_base: {:.2}, dry_allowed_length: {}, lz_penalty: {:.2} }}",
                c.temperature,
                c.top_p,
                c.top_k,
                c.presence_penalty,
                c.frequency_penalty,
                c.repetition_penalty,
                c.dry_multiplier,
                c.dry_base,
                c.dry_allowed_length,
                c.lz_penalty,
            )
        };
        g.push_str(&format!(
            "        TargetPtxSet {{\n\
             \x20           target: KernelTarget {{ arch: \"{arch_clean}\", model: \"{}\", quant: \"{}\" }},\n\
             \x20           modules: {fn_name}(),\n\
             \x20           sampling: SamplingPresets {{\n\
             \x20               thinking_text: {},\n\
             \x20               thinking_coding: {},\n\
             \x20               non_thinking: {},\n\
             \x20               tools: {},\n\
             \x20           }},\n\
             \x20           behavior: ModelBehavior {{\n\
             \x20               thinking_in_tools: {},\n\
             \x20               max_thinking_budget: {},\n\
             \x20               thinking_default: {},\n\
             \x20               fp8_kv_calibration_tokens: {},\n\
             \x20               default_kv_dtype: \"{}\",\n\
             \x20               default_num_drafts: {},\n\
             \x20               disable_tool_steering: {},\n\
             \x20               tool_call_parser: \"{}\",\n\
             \x20               enable_loop_watchdog: {},\n\
             \x20           }},\n\
             \x20           model_type_matches: vec![{}],\n\
             \x20           dflash: {},\n\
             \x20       }},\n",
            target.model, target.quant,
            fmt_cat(&target.sampling_thinking_text),
            fmt_cat(&target.sampling_thinking_coding),
            fmt_cat(&target.sampling_non_thinking),
            fmt_cat(&target.sampling_tools),
            target.behavior_thinking_in_tools,
            target.behavior_max_thinking_budget,
            target.behavior_thinking_default,
            target.behavior_fp8_kv_calibration_tokens,
            target.behavior_default_kv_dtype,
            target.behavior_default_num_drafts,
            target.behavior_disable_tool_steering,
            target.behavior_tool_call_parser,
            target.behavior_enable_loop_watchdog,
            target.model_type_matches.iter().map(|m| {
                let hs = match m.hidden_size {
                    Some(v) => format!("Some({v})"),
                    None => "None".to_string(),
                };
                format!("ModelTypeMatch {{ model_type: \"{}\", hidden_size: {hs} }}", m.model_type)
            }).collect::<Vec<_>>().join(", "),
            match &target.dflash {
                None => "None".to_string(),
                Some(d) => format!(
                    "Some(DflashConfig {{ draft_model: \"{}\", gamma: {}, window_size: {}, mask_token_id: {}, target_layer_ids: &[{}] }})",
                    d.draft_model, d.gamma, d.window_size, d.mask_token_id,
                    d.target_layer_ids.iter().map(|x| x.to_string()).collect::<Vec<_>>().join(", "),
                ),
            },
        ));
    }
    g.push_str("    ]\n}\n");

    g
}

/// Locate the SCALE (scale-lang.com) install root for the AMD/`scale`
/// vendor path. A SCALE root is the extracted `scale-<ver>-Linux` dir that
/// contains `bin/scaleenv` and a `targets/` dir (per-arch toolchains).
///
/// Resolution order: `$SCALE_HOME` / `$SCALE_ROOT` (exact root), then a
/// short list of conventional locations, then a shallow scan of `$HOME`
/// and `/opt` for a `scale*-Linux` child. Fails fast (PCND) — no silent
/// default — since an AMD build is meaningless without SCALE.
pub(super) fn find_scale_dir() -> PathBuf {
    let is_scale_root =
        |p: &PathBuf| -> bool { p.join("bin/scaleenv").exists() && p.join("targets").is_dir() };

    for var in ["SCALE_HOME", "SCALE_ROOT"] {
        if let Ok(v) = env::var(var) {
            let p = PathBuf::from(&v);
            if is_scale_root(&p) {
                return p;
            }
            panic!(
                "${var}={v} is not a SCALE install root \
                 (expected bin/scaleenv + targets/)."
            );
        }
    }

    let home = env::var("HOME").unwrap_or_default();
    let mut candidates: Vec<PathBuf> = vec![
        PathBuf::from(&home).join("scale17/scale-1.7.0-Linux"),
        PathBuf::from(&home).join("scale/scale-1.7.0-Linux"),
        PathBuf::from("/opt/scale/scale-1.7.0-Linux"),
        PathBuf::from("/opt/scale"),
    ];
    // Shallow scan: a `scale*-Linux` dir directly under $HOME, ~/scale*,
    // or /opt (covers version drift without hardcoding the version).
    for base in [PathBuf::from(&home), PathBuf::from("/opt")] {
        if let Ok(rd) = std::fs::read_dir(&base) {
            for e in rd.flatten() {
                let p = e.path();
                if p.is_dir() {
                    let name = p.file_name().and_then(|n| n.to_str()).unwrap_or("");
                    if name.starts_with("scale") {
                        candidates.push(p.clone());
                        // one level down: ~/scaleNN/scale-<ver>-Linux
                        if let Ok(inner) = std::fs::read_dir(&p) {
                            for ie in inner.flatten() {
                                let ip = ie.path();
                                if ip.is_dir()
                                    && ip
                                        .file_name()
                                        .and_then(|n| n.to_str())
                                        .map(|n| n.starts_with("scale"))
                                        .unwrap_or(false)
                                {
                                    candidates.push(ip);
                                }
                            }
                        }
                    }
                }
            }
        }
    }
    for c in &candidates {
        if is_scale_root(c) {
            return c.clone();
        }
    }
    panic!(
        "SCALE not found. Set $SCALE_HOME to the scale-<ver>-Linux install \
         root (containing bin/scaleenv + targets/), or install SCALE from \
         scale-lang.com. Searched: {candidates:?}"
    );
}

pub(super) fn find_cuda_dir() -> PathBuf {
    if let Ok(cuda_home) = env::var("CUDA_HOME") {
        return PathBuf::from(cuda_home);
    }
    for path in &[
        "/usr/local/cuda",
        "/usr/local/cuda-13.0",
        "/usr/local/cuda-13",
    ] {
        let p = PathBuf::from(path);
        if p.join("bin/nvcc").exists() {
            return p;
        }
    }
    panic!("CUDA not found. Set CUDA_HOME or install CUDA toolkit.");
}
