// SPDX-License-Identifier: AGPL-3.0-only

//! Emit the FibQuant codebook for `(head_dim, k, N)` as a C `__constant__`
//! array, so the `.cu` kernels and the host codec share the exact same
//! codewords (built from the deterministic seed in `FibQuantCodec`).
//!
//! Usage: `cargo run --release -p atlas-quant --example emit_fibquant_codebook 256 4 256`

use atlas_quant::fibquant::FibQuantCodec;
use std::env;

fn main() {
    let args: Vec<String> = env::args().collect();
    let d: usize = args.get(1).and_then(|s| s.parse().ok()).unwrap_or(256);
    let k: usize = args.get(2).and_then(|s| s.parse().ok()).unwrap_or(4);
    let n: usize = args.get(3).and_then(|s| s.parse().ok()).unwrap_or(256);

    let codec = FibQuantCodec::new(d, k, n, 0xF1B0_0A0B_7041);
    let cb = &codec.codebook;
    assert_eq!(cb.k, k);
    assert_eq!(cb.n, n);

    println!("// FibQuant codebook for d={d}, k={k}, N={n} (rate = {:.3} b/coord, {:.1}x vs bf16)",
             codec.rate_bits(),
             codec.compression_vs_fp16());
    println!("// Generated by atlas-quant/examples/emit_fibquant_codebook.rs — deterministic");
    println!("// (ChaCha8 seed 0xF1B0_0A0B_7041). Codewords are k-dim unit-ball vectors");
    println!("// (spherical-Beta f_{{d,k}} optimal). Paste into the .cu as __constant__.");
    println!(
        "__device__ __constant__ float FIB_CODEBOOK[{total}] = {{",
        total = n * k
    );
    for i in 0..n {
        let mut row = String::from("    ");
        for j in 0..k {
            let v = cb.words[i * k + j];
            row.push_str(&format!("{:+.6e}, ", v));
        }
        println!("{row}  // codeword {i}");
    }
    println!("}};");
    println!("\n#define FIB_K {k}");
    println!("#define FIB_N {n}");
}
